name: test

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
        node:
          - 8.15.0
          - 10.15.0
          - 12.0.0
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install
        run: yarn
      - name: Test
        run: yarn ava
